---
version: 2
jobs:
  build:
    docker:
      - image: dickeyxxx/cli-engine-docker:v2.0.0
    working_directory: /tmp/cli-engine
    parallelism: 3
    steps:
      - checkout
      - restore_cache:
          keys:
            - cli-engine-{{ .Branch }}-{{checksum "package.json"}}
            - cli-engine-{{ .Branch }}
            - cli-engine-master
      - run: git submodule sync && git submodule update --init --recursive --remote
      - run: yarn --prefer-offline
      - run:
          command: |
            set -x
            mkdir -p /tmp/test-results
            export TEST_REPORT_PATH=/tmp/test-results
            jest \
              --testResultsProcessor=jest-junit-reporter \
              --coverage \
              --runInBand \
              $(circleci tests glob "src/**/*.test.js" | circleci tests split --split-by=timings)
            bash <(curl -s https://codecov.io/bash) -s coverage
      - run:
          command: |
            set -x
            ./bin/version
            flow check
            eslint .
      - store_test_results:
          path: /tmp/test-results
      - save_cache:
          key: cli-engine-{{ .Branch}}-{{checksum "package.json"}}
          paths:
            - /tmp/cli-engine/node_modules
            - /tmp/cli-engine/npm-packages-offline-cache
            - /tmp/cli-engine/yarn
            - /usr/local/share/.cache/yarn
      - save_cache:
          key: cli-engine-{{ .Branch}}
          paths:
            - /tmp/cli-engine/yarn
            - /usr/local/share/.cache/yarn
