---
version: 2
jobs:
  build:
    docker:
      - image: dickeyxxx/cli-engine-docker:v2.0.0
    working_directory: /tmp/cli-engine
    parallelism: 3
    steps:
      - checkout
      - restore_cache:
          keys:
            - cli-engine-{{ .Branch }}-{{checksum "package.json"}}
            - cli-engine-{{ .Branch }}
            - cli-engine-master
      # clear cache
      - run: rm -rf /tmp/cli-engine/node_modules /tmp/cli-engine/npm-packages-offline-cache /tmp/cli-engine/yarn /usr/local/share/.cache
      - run: ls /.circleci-task-data/circle-test-results/
      - run: git submodule sync && git submodule update --init --recursive --remote
      - run: yarn --prefer-offline
      - run:
          command: |
            set -x
            mkdir -p /tmp/test-results
            export JEST_JUNIT_OUTPUT=/tmp/test-results/junit.xml
            export JEST_USE_PATH_FOR_SUITE_NAME=true
            jest \
              --testResultsProcessor=jest-junit \
              --coverage \
              --runInBand \
              $(circleci tests glob "src/**/*.test.js" | circleci tests split --split-by=timings)
            bash <(curl -s https://codecov.io/bash) -s coverage
            cat $JEST_JUNIT_OUTPUT
      - run:
          command: |
            set -x
            ./bin/version
            flow check
            eslint .
      - store_test_results:
          path: /tmp/test-results
      - save_cache:
          key: cli-engine-{{ .Branch}}-{{checksum "package.json"}}
          paths:
            - /tmp/cli-engine/node_modules
            - /tmp/cli-engine/npm-packages-offline-cache
            - /tmp/cli-engine/yarn
            - /usr/local/share/.cache/yarn
      - save_cache:
          key: cli-engine-{{ .Branch}}
          paths:
            - /tmp/cli-engine/yarn
            - /usr/local/share/.cache/yarn
